export const environment = {
  PRODUCTION: false,
  IS_LOCAL: false,
  DEBUG: true,
  TERMS_OF_USE_URL: 'https://develop-client-www.caseactive.net/term-of-service',
  ACCOUNT_API_URL: 'https://develop-api-account.caseactive.net',
  ACCOUNT_CLIENT_URL: 'https://develop-client-account.caseactive.net',
  APP_API_URL: 'https://develop-api-app.caseactive.net',
  APP_CLIENT_URL: 'https://*.develop-client-app.caseactive.net',
  CASE_USERS_LIMIT: '20',
  HOST_ROLES_LIMIT: '20',
  INTEGRATION_APP_KEYS_LIMIT: '2',
  INTEGRATION_MANAGE_KEYS_LIMIT: '2',
  INTEGRATION_WEBHOOK_LIMIT: '5',
  MANAGE_CLIENT_URL: 'https://*.develop-client-manage.caseactive.net',
  MANAGE_API_URL: 'https://develop-api-manage.caseactive.net',
  PRIVATE_CDN_URL: 'https://develop-cdn-private.caseactive.net',
  PUBLIC_CDN_URL: 'https://develop-cdn-public.caseactive.net',
  RECAPTCHA_KEY: '6LdG3twZAAAAAG6zJgM6nUoPVfSaMfcWSgVW0FDp',
  ROLLBACKS_BUCKET: 'ca-develop-rollbacks-caseactive',
  WWW_CLIENT_URL: 'https://develop-client-www.caseactive.net',
  GOOGLE_CLOUD_PUBLIC_API_KEY: 'AIzaSyDshV9mhMWdJehSCwHtFzNXuEsnTEe0nJk',
  AWS_REGION: 'us-east-1',
  AWS_DEFAULT_REGION: 'us-east-1',
  GOOGLE_REGION: 'us-east4',
  SQUARE_APPLICATION_ID: 'sandbox-sq0idb-GhnlxCAYKVujdJOpg8kobA',
  STRIPE_PUBLIC_API_KEY:
    'pk_test_51IzRxbFfbnN34GIGUNptwHYHsj4ifKqB1KSggOiQv0KqXhHZ8DLpZmHbYMnfAs2ZsXq1yRu1Csjug5RSAMdPxvBs00b26q62op'
};
